nodeLinker: node-modules

packageExtensions:
  "@apollo/react-hooks@*":
    peerDependencies:
      graphql: ^15.8.0
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint: ^6.8.0
      eslint-plugin-import: ^2.22.1
      eslint-plugin-jsx-a11y: ^6.5.1
      eslint-plugin-react: ^7.23.1
      eslint-plugin-react-hooks: ^2.5.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
